project_id = "tgxiqvfpirwvhktgqqfa"

[functions.google-drive]
verify_jwt = false

[functions.onedrive]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.economic-indicators]
verify_jwt = false

[functions.send-contract-email]
verify_jwt = false

[functions.process-alerts]
verify_jwt = false

[functions.extract-contract-data]
verify_jwt = false

[functions.process-patent-alerts]
verify_jwt = false

[functions.summarize-text]
verify_jwt = false

[functions.recommend-form-time]
verify_jwt = false

[functions.nearby-hardware-stores]
verify_jwt = false

[functions.refresh-economic-indicators]
verify_jwt = false

[functions.match-contracts]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
